---
sudo: required
dist: trusty

services:
  - docker

before_install:
  - sudo apt-get install -y curl

script:
  # Build docker image
  - cd 9.1/
  - docker build -t maestrano/web-jruby:travis . > /dev/null 2>&1

  #=======================================
  # Test with minimal parameters
  #=======================================
  # Run image
  - docker run -P -d --name travis-test -e GIT_URL=https://github.com/maestrano/sample_app_rails_4 -e GIT_BRANCH=master maestrano/web-jruby:travis

  # Get ip address
  - "container_ip=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' travis-test`"

  # Wait for container to be ready
  - try_count=0;
  - HEALTH_CHECK="starting"
  - while [ "$HEALTH_CHECK" == "starting" ] || [ "$HEALTH_CHECK" == "unhealthy" ]; do let "try_count++"; [ $try_count -gt 100 ] && exit 20; sleep 5; HEALTH_CHECK=$(docker inspect --format='{{.State.Health.Status}}' travis-test 2>/dev/null); done

  # Check that application is up
  - "curl http://${container_ip}:80/"

  # Remove container
  - docker rm -f travis-test

  #=======================================
  # Test with S3
  #=======================================
  # Run image
  - docker run -P -d --name travis-test -e S3_URI=s3://cdn-prd-maestrano/pkg/sample/sample_app_rails.tar.gz -e S3_REGION=ap-southeast-1 maestrano/web-jruby:travis

  # Get ip address
  - "container_ip=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' travis-test`"

  # Wait for container to be ready
  - try_count=0;
  - HEALTH_CHECK="starting"
  - while [ "$HEALTH_CHECK" == "starting" ] || [ "$HEALTH_CHECK" == "unhealthy" ]; do let "try_count++"; [ $try_count -gt 100 ] && exit 20; sleep 5; HEALTH_CHECK=$(docker inspect --format='{{.State.Health.Status}}' travis-test 2>/dev/null); done

  # Check that application is up
  - "curl http://${container_ip}:80/"

  # Remove container
  - docker rm -f travis-test

  #=======================================
  # Test with foreman options
  #=======================================
  # Run image
  - docker run -P -d --name travis-test -e FOREMAN_OPTS="-m web=1" -e GIT_URL=https://github.com/maestrano/sample_app_rails_4 -e GIT_BRANCH=master maestrano/web-jruby:travis

  # Get ip address
  - "container_ip=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' travis-test`"

  # Wait for container to be ready
  - try_count=0;
  - HEALTH_CHECK="starting"
  - while [ "$HEALTH_CHECK" == "starting" ] || [ "$HEALTH_CHECK" == "unhealthy" ]; do let "try_count++"; [ $try_count -gt 100 ] && exit 20; sleep 5; HEALTH_CHECK=$(docker inspect --format='{{.State.Health.Status}}' travis-test 2>/dev/null); done

  # Check that application is up
  - "curl http://${container_ip}:80/"

  # Remove container
  - docker rm -f travis-test

  #=======================================
  # Test with Gemstash server
  #=======================================
  # Run gemstash server
  - docker run -P -d --name gemstash maestrano/gemstash

  # Get gemstash ip address
  - "gemstash_ip=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' gemstash`"

  # Run image
  - docker run -P -d --name travis-test -e GEMSTASH_SERVER="http://${gemstash_ip}:9292" -e GIT_URL=https://github.com/maestrano/sample_app_rails_4 -e GIT_BRANCH=master maestrano/web-jruby:travis

  # Get ip address
  - "container_ip=`docker inspect --format '{{ .NetworkSettings.IPAddress }}' travis-test`"

  # Wait for container to be ready
  - try_count=0;
  - HEALTH_CHECK="starting"
  - while [ "$HEALTH_CHECK" == "starting" ] || [ "$HEALTH_CHECK" == "unhealthy" ]; do let "try_count++"; [ $try_count -gt 100 ] && exit 20; sleep 5; HEALTH_CHECK=$(docker inspect --format='{{.State.Health.Status}}' travis-test 2>/dev/null); done

  # Check that application is up
  - "curl http://${container_ip}:80/"

  # Remove container
  - docker rm -f travis-test
